---
- hosts: builders
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
  - name: install pip3
    apt: name=python3-pip state=present 
    become: true
  - name: install certain python modules for docker
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: present
    with_items:
    - { name: docker, version: 6.0.1 }
  - name: Build aurora image
    docker_image:
      path: .
      name: aalekseevx/aurora
      push: true
      source: build
 
